# Generated by Django 5.1.1 on 2025-02-15 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaccion",
            old_name="categoria",
            new_name="categoriaID",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="cuenta",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="usuario",
        ),
        migrations.AddField(
            model_name="cuenta",
            name="userID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="cuentaID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financeApp.cuenta",
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="cuentaID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financeApp.cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="transaccion",
            name="fecha",
            field=models.DateField(),
        ),
    ]
