# Generated by Django 5.1.1 on 2025-02-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeApp", "0002_rename_categoria_transaccion_categoriaid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="alias",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="cvu",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="nombre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="monto_maximo",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
