services:
  db:
    image: mysql:8
    container_name: mysql_finanzas
    restart: always
    environment:
      MYSQL_DATABASE: financeDB
      MYSQL_USER: tadeo
      MYSQL_PASSWORD: pass1234
      MYSQL_ROOT_PASSWORD: pass1234
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
